// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RifaCasinoAPI;

#nullable disable

namespace RifaCasinoAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220518102812_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RifaCasinoAPI.Entidades.Participaciones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("idParticipante")
                        .HasColumnType("int");

                    b.Property<int>("idRifa")
                        .HasColumnType("int");

                    b.Property<int?>("participanteid")
                        .HasColumnType("int");

                    b.Property<int?>("rifaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("participanteid");

                    b.HasIndex("rifaid");

                    b.ToTable("Participaciones");
                });

            modelBuilder.Entity("RifaCasinoAPI.Entidades.Participantes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("RifaCasinoAPI.Entidades.Premio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("disponible")
                        .HasColumnType("bit");

                    b.Property<int>("idRifa")
                        .HasColumnType("int");

                    b.Property<int?>("rifaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("rifaid");

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("RifaCasinoAPI.Entidades.Rifa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("vigente")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Rifas");
                });

            modelBuilder.Entity("RifaCasinoAPI.Entidades.Participaciones", b =>
                {
                    b.HasOne("RifaCasinoAPI.Entidades.Participantes", "participante")
                        .WithMany("participacionesList")
                        .HasForeignKey("participanteid");

                    b.HasOne("RifaCasinoAPI.Entidades.Rifa", "rifa")
                        .WithMany("particiones")
                        .HasForeignKey("rifaid");

                    b.Navigation("participante");

                    b.Navigation("rifa");
                });

            modelBuilder.Entity("RifaCasinoAPI.Entidades.Premio", b =>
                {
                    b.HasOne("RifaCasinoAPI.Entidades.Rifa", "rifa")
                        .WithMany("premioList")
                        .HasForeignKey("rifaid");

                    b.Navigation("rifa");
                });

            modelBuilder.Entity("RifaCasinoAPI.Entidades.Participantes", b =>
                {
                    b.Navigation("participacionesList");
                });

            modelBuilder.Entity("RifaCasinoAPI.Entidades.Rifa", b =>
                {
                    b.Navigation("particiones");

                    b.Navigation("premioList");
                });
#pragma warning restore 612, 618
        }
    }
}
