using RifaCasinoAPI.Entidades;

namespace RifaCasinoAPI.Utilidades
{
    public class NumerosRifaPreset
    {
        public List<Tarjeta> tarjetas = new List<Tarjeta> {
            new Tarjeta(1,"ElGallo","El que cantó a San Pedro, no volverá a cantar."),
            new Tarjeta(2,"ElDiablo","El diablo son las mujeres, cuando se quieren casar."),
            new Tarjeta(3,"LaDama","La chula de Severiana un tacón quería empeñar."),
            new Tarjeta(4,"ElCatrín","Don Ferruco en la Alameda su bastón quería empeñar."),
            new Tarjeta(5,"ElParaguas","El paraguas quitasol."),
            new Tarjeta(6,"LaSirena","Medio cuerpo de sirena, medio cuerpo de mujer."),
            new Tarjeta(7,"LaEscalera","La escalera, siete palos, la escalera del pintor."),
            new Tarjeta(8,"LaBotella","La botella del tequila, la botella del mezcal."),
            new Tarjeta(9,"ElBarril","El barril es quintaleño, el barril del mezcal."),
            new Tarjeta(10,"ElÁrbol","El árbol de la esperanza que de venir no se cansa."),
            new Tarjeta(11,"ElMelón","El melón y sus olores, un pedazo me has de dar."),
            new Tarjeta(12,"ElValite","’Tate quieto, Valentín, no te vayas a pelear."),
            new Tarjeta(13,"ElGorrito","El gorrito ponle al nene, no se te vaya a resfriar."),
            new Tarjeta(14,"LaMuerte","La muerte siriquiflaca, montada en su burra flaca."),
            new Tarjeta(15,"LaPera","Me esperas donde quedamos, para poder platicar."),
            new Tarjeta(16,"LaBandera","Bonito cinco de mayo, el pabellón nacional."),
            new Tarjeta(17,"ElBandolón","El bandolón ya no suena, hay que llevarlo a afinar."),
            new Tarjeta(18,"ElVioloncello","El violoncello del maistro, que no deja de sonar."),
            new Tarjeta(19,"LaGarza","Llegaron los picos largos de la feria de San Juan."),
            new Tarjeta(20,"ElPájaro","El pájaro churlumirlo, que no deja de cantar."),
            new Tarjeta(21,"LaMano","La mano del escribano, la mano del criminal."),
            new Tarjeta(22,"LaBota","La bota rechina, la bota del general."),
            new Tarjeta(23,"LaLuna","La luna tuerta de un ojo, que no deja de brillar."),
            new Tarjeta(24,"ElCotorro","Perico, da’cá la pata y empiézame a platicar los trabajos que pasabas cuando no sabías hablar."),
            new Tarjeta(25,"ElBorracho","Al borracho, mi compañero, ya se lo van a cargar."),
            new Tarjeta(26,"ElNegrito","Para negros, en La Habana; uno acaba de llegar."),
            new Tarjeta(27,"ElCorazón","El corazón de una ingrata yo lo voy a traspasar."),
            new Tarjeta(28,"LaSandía","La sandía y su rebanada, un pedazo me has de dar."),
            new Tarjeta(29,"ElTambor","No te arrugues, cuero viejo, que te quiero pa’ tambor."),
            new Tarjeta(30,"ElCamarón","Camarón que se duerme se lo lleva la corriente."),
            new Tarjeta(31,"LasJaras","Las jaras o no las jaras, o las dejas de jalar."),
            new Tarjeta(32,"ElMúsico","El músico, trompa de hule."),
            new Tarjeta(33,"LaAraña","La araña teje su tela."),
            new Tarjeta(34,"ElSoldado","Centinela, ponte alerta, que te habla tu general"),
            new Tarjeta(35,"LaEstrella","La estrella polar del norte, que no deja de brillar."),
            new Tarjeta(36,"ElCazo","El caso que te hago es poco; el caso es averiguar."),
            new Tarjeta(37,"ElMundo","El mundo es una bola, y nosotros, un bolón."),
            new Tarjeta(38,"ElApache","Para apaches, en Chihuahua; uno acaba de llegar."),
            new Tarjeta(39,"ElNopal","El auxilio de San Luis, que le llaman el nopal."),
            new Tarjeta(40,"ElAlacrán","¡No levantes esa piedra, que te pica ese animal!"),
            new Tarjeta(41,"LaRosa","Rosa, Rosita, Rosaura, Rosita se ha de llamar."),
            new Tarjeta(42,"LaCalavera","Ya te vide an ca’ la güera."),
            new Tarjeta(43,"LaCampana","La campana, y tú, debajo."),
            new Tarjeta(44,"ElCantarito","Todo cabe en un jarrito, sabiéndolo acomodar."),
            new Tarjeta(45,"ElVenado","Don Venancio, a la carrera, un balazo le han de dar."),
            new Tarjeta(46,"ElSol","Solito me estoy quedando, solito me he de quedar."),
            new Tarjeta(47,"LaCorona","Si te mueres, te la pongo, la coronita imperial."),
            new Tarjeta(48,"LaChalupa","Rema y rema, Joaquinita, y no dejes de remar."),
            new Tarjeta(49,"ElPino","Te empino y me voy de paso, y empinado has de quedar."),
            new Tarjeta(50,"ElPescado","Me pescaron vacilando en la puerta del zaguán."),
            new Tarjeta(51,"LaPalma","Sube a la palma, palmero, y bájame un cocotal."),
            new Tarjeta(52,"LaMaceta","En la maceta me dieron, por no saber barajar."),
            new Tarjeta(53,"ElArpa","El arpa vieja de mi suegra."),
            new Tarjeta(54,"LaRana","¡Qué saltos pega tu hermana en la puerta del zaguán!")
        };
    }
}